-- 03 · 제약 (기본키 → 유일 → 체크 → 외래키)
-- 스냅샷: 2026-09-28 · 원본 DB 와 md5 대조 완료 (verify.sql)

alter table public.accounts add constraint accounts_pkey PRIMARY KEY (id);
alter table public.app_settings add constraint app_settings_pkey PRIMARY KEY (owner_id, key);
alter table public.asset_snapshots add constraint asset_snapshots_pkey PRIMARY KEY (id);
alter table public.braindump_archive add constraint braindump_archive_pkey PRIMARY KEY (id);
alter table public.braindump_blocks add constraint braindump_blocks_pkey PRIMARY KEY (id);
alter table public.career_positions add constraint career_positions_pkey PRIMARY KEY (id);
alter table public.categories add constraint categories_pkey PRIMARY KEY (id);
alter table public.characters add constraint characters_pkey PRIMARY KEY (id);
alter table public.countries add constraint countries_pkey PRIMARY KEY (id);
alter table public.date_balance_checks add constraint date_balance_checks_pkey PRIMARY KEY (id);
alter table public.date_books add constraint date_books_pkey PRIMARY KEY (id);
alter table public.date_members add constraint date_members_pkey PRIMARY KEY (book_id, user_id);
alter table public.date_tx add constraint date_tx_pkey PRIMARY KEY (id);
alter table public.drawings add constraint drawings_pkey PRIMARY KEY (id);
alter table public.goal_files add constraint goal_files_pkey PRIMARY KEY (id);
alter table public.goal_links add constraint goal_links_pkey PRIMARY KEY (id);
alter table public.goals add constraint goals_pkey PRIMARY KEY (id);
alter table public.holdings add constraint holdings_pkey PRIMARY KEY (id);
alter table public.job_applications add constraint job_applications_pkey PRIMARY KEY (id);
alter table public.life_event_people add constraint life_event_people_pkey PRIMARY KEY (event_id, person_id);
alter table public.life_events add constraint life_events_pkey PRIMARY KEY (id);
alter table public.life_group_people add constraint life_group_people_pkey PRIMARY KEY (group_id, person_id);
alter table public.life_groups add constraint life_groups_pkey PRIMARY KEY (id);
alter table public.life_people add constraint life_people_pkey PRIMARY KEY (id);
alter table public.media_characters add constraint media_characters_pkey PRIMARY KEY (media_id, character_id);
alter table public.media_collection_items add constraint media_collection_items_pkey PRIMARY KEY (collection_id, media_id);
alter table public.media_collections add constraint media_collections_pkey PRIMARY KEY (id);
alter table public.media_countries add constraint media_countries_pkey PRIMARY KEY (media_id, country_id);
alter table public.media_credits add constraint media_credits_pkey PRIMARY KEY (id);
alter table public.media_items add constraint media_items_pkey PRIMARY KEY (id);
alter table public.media_relations add constraint media_relations_pkey PRIMARY KEY (from_id, to_id);
alter table public.media_series add constraint media_series_pkey PRIMARY KEY (id);
alter table public.media_tags add constraint media_tags_pkey PRIMARY KEY (media_id, tag_id);
alter table public.merchant_groups add constraint merchant_groups_pkey PRIMARY KEY (id);
alter table public.merchants add constraint merchants_pkey PRIMARY KEY (id);
alter table public.people add constraint people_pkey PRIMARY KEY (id);
alter table public.routine_logs add constraint routine_logs_pkey PRIMARY KEY (id);
alter table public.routine_spans add constraint routine_spans_pkey PRIMARY KEY (id);
alter table public.routines add constraint routines_pkey PRIMARY KEY (id);
alter table public.stocks add constraint stocks_pkey PRIMARY KEY (id);
alter table public.study_cards add constraint study_cards_pkey PRIMARY KEY (id);
alter table public.tags add constraint tags_pkey PRIMARY KEY (id);
alter table public.themes add constraint themes_pkey PRIMARY KEY (id);
alter table public.transactions add constraint transactions_pkey PRIMARY KEY (id);
alter table public.accounts add constraint accounts_owner_id_name_key UNIQUE (owner_id, name);
alter table public.asset_snapshots add constraint asset_snapshots_owner_id_month_account_key UNIQUE (owner_id, month, account);
alter table public.braindump_archive add constraint braindump_archive_uniq UNIQUE (owner_id, entry_date);
alter table public.categories add constraint categories_owner_id_kind_category_subcategory_key UNIQUE (owner_id, kind, category, subcategory);
alter table public.date_books add constraint date_books_invite_code_key UNIQUE (invite_code);
alter table public.goal_links add constraint goal_links_uniq UNIQUE (from_goal_id, to_goal_id, kind);
alter table public.holdings add constraint holdings_owner_id_snapshot_at_name_key UNIQUE (owner_id, snapshot_at, name);
alter table public.life_groups add constraint life_groups_owner_id_name_key UNIQUE (owner_id, name);
alter table public.life_people add constraint life_people_owner_id_name_key UNIQUE (owner_id, name);
alter table public.merchants add constraint merchants_owner_name UNIQUE (owner_id, name);
alter table public.routine_logs add constraint routine_logs_routine_id_on_date_key UNIQUE (routine_id, on_date);
alter table public.stocks add constraint stocks_owner_id_name_key UNIQUE (owner_id, name);
alter table public.study_cards add constraint study_cards_owner_name UNIQUE (owner_id, name);
alter table public.tags add constraint tags_owner_id_kind_name_key UNIQUE (owner_id, kind, name);
alter table public.themes add constraint themes_owner_id_name_key UNIQUE (owner_id, name);
alter table public.accounts add constraint accounts_asset_class_check CHECK ((asset_class = ANY (ARRAY['현금 자산'::text, '투자 자산'::text, '저축 자산'::text, '연금 자산'::text, '부채 자산'::text])));
alter table public.braindump_blocks add constraint braindump_blocks_block_type_check CHECK ((block_type = ANY (ARRAY['task'::text, 'text'::text, 'bullet'::text, 'spacer'::text])));
alter table public.braindump_blocks add constraint braindump_blocks_section_check CHECK ((section = ANY (ARRAY['work'::text, 'personal'::text])));
alter table public.braindump_blocks add constraint braindump_bucket_check CHECK ((bucket = ANY (ARRAY['today'::text, 'someday'::text])));
alter table public.braindump_blocks add constraint braindump_event_clean CHECK ((is_event OR ((event_on IS NULL) AND (event_at IS NULL) AND (event_end IS NULL) AND (event_place IS NULL) AND (event_with IS NULL))));
alter table public.braindump_blocks add constraint braindump_only_task_done CHECK (((done_on IS NULL) OR (block_type = 'task'::text)));
alter table public.braindump_blocks add constraint braindump_priority_range CHECK (((priority >= 0) AND (priority <= 3)));
alter table public.categories add constraint categories_kind_check CHECK ((kind = ANY (ARRAY['수입'::text, '지출'::text, '이체'::text, '자산'::text])));
alter table public.date_tx add constraint date_tx_amount_check CHECK ((amount > (0)::numeric));
alter table public.date_tx add constraint date_tx_depositor_on_deposit CHECK (((kind = '입금'::text) = (depositor IS NOT NULL)));
alter table public.date_tx add constraint date_tx_good_bad_check CHECK ((good_bad = ANY (ARRAY['Good'::text, 'Bad'::text])));
alter table public.date_tx add constraint date_tx_kind_check CHECK ((kind = ANY (ARRAY['지출'::text, '입금'::text, '수입'::text])));
alter table public.goal_links add constraint goal_links_kind_check CHECK ((kind = ANY (ARRAY['prereq'::text, 'next'::text, 'related'::text])));
alter table public.goal_links add constraint goal_links_no_self CHECK ((from_goal_id <> to_goal_id));
alter table public.goals add constraint goals_metric_source_check CHECK (((metric_source IS NULL) OR (metric_source = ANY (ARRAY['total_asset'::text, 'available_asset'::text, 'asset_class'::text, 'monthly_expense'::text, 'fixed_cost'::text, 'invest_income'::text, 'position_max_ratio'::text, 'media_count'::text]))));
alter table public.goals add constraint goals_status_check CHECK ((status = ANY (ARRAY['대기'::text, '진행중'::text, '달성/완료'::text, '중단'::text])));
alter table public.life_events add constraint life_events_kind_ck CHECK ((kind = ANY (ARRAY['출생·가족'::text, '학업'::text, '일·커리어'::text, '관계·만남'::text, '성취·합격'::text, '거처·이사'::text, '여행'::text, '건강'::text, '상실'::text, '일상'::text])));
alter table public.life_events add constraint life_events_precision_ck CHECK (("precision" = ANY (ARRAY['day'::text, 'month'::text, 'year'::text])));
alter table public.life_events add constraint life_events_weight_ck CHECK ((weight = ANY (ARRAY['이정표'::text, '기억'::text, '스침'::text])));
alter table public.media_credits add constraint media_credits_role_chk CHECK ((role = ANY (ARRAY['주창작'::text, '참여'::text, '출연'::text, '제작'::text])));
alter table public.media_relations add constraint media_relations_kind_chk CHECK ((kind = ANY (ARRAY['related'::text, 'source'::text])));
alter table public.people add constraint people_kind_chk CHECK ((kind = ANY (ARRAY['person'::text, 'org'::text])));
alter table public.routine_logs add constraint routine_logs_status_ck CHECK ((status = ANY (ARRAY['done'::text, 'miss'::text, 'na'::text])));
alter table public.routines add constraint routines_freq_ck CHECK ((freq_type = ANY (ARRAY['daily'::text, 'week_n'::text, 'weekdays'::text, 'month_n'::text, 'every_n'::text])));
alter table public.routines add constraint routines_time_slot_check CHECK (((time_slot IS NULL) OR (time_slot = ANY (ARRAY['morning'::text, 'noon'::text, 'evening'::text, 'anytime'::text]))));
alter table public.study_cards add constraint study_cards_watch_level_chk CHECK (((watch_level IS NULL) OR (watch_level = ANY (ARRAY['L1'::text, 'L2'::text, 'L3'::text]))));
alter table public.transactions add constraint transactions_good_bad_check CHECK ((good_bad = ANY (ARRAY['Good'::text, 'Bad'::text])));
alter table public.braindump_archive add constraint braindump_archive_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.braindump_blocks add constraint braindump_blocks_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.braindump_blocks add constraint braindump_blocks_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES braindump_blocks(id) ON DELETE CASCADE;
alter table public.career_positions add constraint career_positions_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.characters add constraint characters_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.countries add constraint countries_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.date_balance_checks add constraint date_balance_checks_book_id_fkey FOREIGN KEY (book_id) REFERENCES date_books(id) ON DELETE CASCADE;
alter table public.date_balance_checks add constraint date_balance_checks_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.date_books add constraint date_books_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.date_members add constraint date_members_book_id_fkey FOREIGN KEY (book_id) REFERENCES date_books(id) ON DELETE CASCADE;
alter table public.date_members add constraint date_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.date_tx add constraint date_tx_book_id_fkey FOREIGN KEY (book_id) REFERENCES date_books(id) ON DELETE CASCADE;
alter table public.date_tx add constraint date_tx_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.drawings add constraint drawings_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.goal_files add constraint goal_files_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE;
alter table public.goal_files add constraint goal_files_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.goal_links add constraint goal_links_from_goal_id_fkey FOREIGN KEY (from_goal_id) REFERENCES goals(id) ON DELETE CASCADE;
alter table public.goal_links add constraint goal_links_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.goal_links add constraint goal_links_to_goal_id_fkey FOREIGN KEY (to_goal_id) REFERENCES goals(id) ON DELETE CASCADE;
alter table public.job_applications add constraint job_applications_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.life_event_people add constraint life_event_people_event_id_fkey FOREIGN KEY (event_id) REFERENCES life_events(id) ON DELETE CASCADE;
alter table public.life_event_people add constraint life_event_people_person_id_fkey FOREIGN KEY (person_id) REFERENCES life_people(id) ON DELETE CASCADE;
alter table public.life_events add constraint life_events_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE SET NULL;
alter table public.life_events add constraint life_events_group_id_fkey FOREIGN KEY (group_id) REFERENCES life_groups(id) ON DELETE SET NULL;
alter table public.life_events add constraint life_events_position_id_fkey FOREIGN KEY (position_id) REFERENCES career_positions(id) ON DELETE SET NULL;
alter table public.life_group_people add constraint life_group_people_group_id_fkey FOREIGN KEY (group_id) REFERENCES life_groups(id) ON DELETE CASCADE;
alter table public.life_group_people add constraint life_group_people_person_id_fkey FOREIGN KEY (person_id) REFERENCES life_people(id) ON DELETE CASCADE;
alter table public.media_characters add constraint media_characters_character_id_fkey FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE;
alter table public.media_characters add constraint media_characters_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_items(id) ON DELETE CASCADE;
alter table public.media_characters add constraint media_characters_person_id_fkey FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE SET NULL;
alter table public.media_collection_items add constraint media_collection_items_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES media_collections(id) ON DELETE CASCADE;
alter table public.media_collection_items add constraint media_collection_items_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_items(id) ON DELETE CASCADE;
alter table public.media_collections add constraint media_collections_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.media_countries add constraint media_countries_country_id_fkey FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE CASCADE;
alter table public.media_countries add constraint media_countries_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_items(id) ON DELETE CASCADE;
alter table public.media_credits add constraint media_credits_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_items(id) ON DELETE CASCADE;
alter table public.media_credits add constraint media_credits_person_id_fkey FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE;
alter table public.media_items add constraint media_items_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.media_items add constraint media_items_series_id_fkey FOREIGN KEY (series_id) REFERENCES media_series(id) ON DELETE SET NULL;
alter table public.media_relations add constraint media_relations_from_id_fkey FOREIGN KEY (from_id) REFERENCES media_items(id) ON DELETE CASCADE;
alter table public.media_relations add constraint media_relations_to_id_fkey FOREIGN KEY (to_id) REFERENCES media_items(id) ON DELETE CASCADE;
alter table public.media_series add constraint media_series_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.media_tags add constraint media_tags_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_items(id) ON DELETE CASCADE;
alter table public.media_tags add constraint media_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE;
alter table public.people add constraint people_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.routine_logs add constraint routine_logs_routine_id_fkey FOREIGN KEY (routine_id) REFERENCES routines(id) ON DELETE CASCADE;
alter table public.routine_spans add constraint routine_spans_routine_id_fkey FOREIGN KEY (routine_id) REFERENCES routines(id) ON DELETE CASCADE;
alter table public.routines add constraint routines_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE SET NULL;
alter table public.tags add constraint tags_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.transactions add constraint transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT;


-- 2026-09-28 토스·종목 팩트 (migrations/20260928000006)
alter table public.toss_summary add constraint toss_summary_pkey PRIMARY KEY (owner_id);
alter table public.toss_holdings add constraint toss_holdings_pkey PRIMARY KEY (owner_id, symbol);
alter table public.toss_daily add constraint toss_daily_pkey PRIMARY KEY (owner_id, date);

-- 코알라 앱 변경 반영 (2026-09-28)
alter table public.drawing_eras add constraint drawing_eras_pkey PRIMARY KEY (id);
alter table public.drawings add constraint drawings_date_prec_check CHECK ((date_prec = ANY (ARRAY['day'::text, 'month'::text, 'season'::text, 'year'::text])));
alter table public.drawing_eras add constraint drawing_eras_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.routine_logs add constraint routine_logs_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_items(id) ON DELETE CASCADE;
