-- 이 폴더의 스냅샷이 지금 DB 와 같은지 확인한다.
-- Supabase SQL 편집기(또는 Claude 의 execute_sql)에서 돌리고, 결과를 expected.md5 와 비교.
-- 다르면 DB 가 바뀐 것 → 이 폴더를 다시 떠서 갱신하거나, 바뀐 내용을 migrations/ 에 기록할 것.
with
tbl as (select c.oid, c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p')),
cols as (
  select tbl.relname, string_agg(
    format('  %I %s%s%s%s', a.attname, format_type(a.atttypid,a.atttypmod),
      case when a.attidentity='a' then ' generated always as identity' when a.attidentity='d' then ' generated by default as identity' else '' end,
      case when ad.adbin is not null and a.attgenerated='' then ' default '||pg_get_expr(ad.adbin,ad.adrelid) when a.attgenerated='s' then ' generated always as ('||pg_get_expr(ad.adbin,ad.adrelid)||') stored' else '' end,
      case when a.attnotnull then ' not null' else '' end), E',\n' order by a.attnum) body
  from tbl join pg_attribute a on a.attrelid=tbl.oid and a.attnum>0 and not a.attisdropped
  left join pg_attrdef ad on ad.adrelid=tbl.oid and ad.adnum=a.attnum
  group by tbl.relname)
select 'seq' part, md5((select string_agg(format('create sequence if not exists public.%I;', c.relname), E'\n' order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace left join pg_depend d on d.objid=c.oid and d.deptype='i' where n.nspname='public' and c.relkind='S' and d.objid is null))
union all select 'tables', md5((select string_agg(format(E'create table public.%I (\n%s\n);', relname, body), E'\n\n' order by relname) from cols))
union all select 'cons', md5((select string_agg(format('alter table public.%I add constraint %I %s;', rel.relname, con.conname, pg_get_constraintdef(con.oid)), E'\n' order by case con.contype when 'p' then 0 when 'u' then 1 when 'c' then 2 else 3 end, rel.relname, con.conname) from pg_constraint con join pg_class rel on rel.oid=con.conrelid join pg_namespace n on n.oid=rel.relnamespace where n.nspname='public' and con.contype in ('p','u','c','f')))
union all select 'idx', md5((select string_agg(i.indexdef||';', E'\n' order by i.tablename, i.indexname) from pg_indexes i where i.schemaname='public' and not exists (select 1 from pg_constraint c where c.conname=i.indexname)))
union all select 'funcs', md5((select string_agg(pg_get_functiondef(p.oid)||';', E'\n' order by p.proname, p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace left join pg_depend d on d.objid=p.oid and d.deptype='e' where n.nspname='public' and d.objid is null and p.prokind in ('f','p')))
union all select 'views', md5((select string_agg(format(E'create or replace view public.%I%s as\n%s', c.relname, case when c.reloptions is not null then ' with ('||array_to_string(c.reloptions,', ')||')' else '' end, rtrim(pg_get_viewdef(c.oid, true))), E'\n\n' order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='v'))
union all select 'trigs', md5((select string_agg(pg_get_triggerdef(t.oid)||';', E'\n' order by c.relname, t.tgname) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and not t.tgisinternal))
union all select 'rls', md5((select string_agg(format('alter table public.%I enable row level security;', c.relname), E'\n' order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and c.relrowsecurity))
union all select 'pols', md5((select string_agg(format(E'create policy %I on public.%I as %s for %s to %s%s%s;', pol.polname, c.relname, case when pol.polpermissive then 'permissive' else 'restrictive' end,
   case pol.polcmd when 'r' then 'select' when 'a' then 'insert' when 'w' then 'update' when 'd' then 'delete' else 'all' end,
   (select string_agg(case when r=0 then 'public' else quote_ident(pg_get_userbyid(r)) end, ', ') from unnest(pol.polroles) r),
   case when pol.polqual is not null then E'\n  using ('||pg_get_expr(pol.polqual, pol.polrelid)||')' else '' end,
   case when pol.polwithcheck is not null then E'\n  with check ('||pg_get_expr(pol.polwithcheck, pol.polrelid)||')' else '' end), E'\n' order by c.relname, pol.polname)
   from pg_policy pol join pg_class c on c.oid=pol.polrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'));
